# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI

on:
  push:
    branches:
      - main
      - dev       
  pull_request:
    branches:
      - main
      - dev       

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Configura el repositorio
      - name: Checkout repository
        uses: actions/checkout@v3

      # Configura JDK
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'  # Cambia la versión según tu proyecto
          distribution: 'temurin'

      # Compila el proyecto y ejecuta pruebas
      - name: Build with Maven
        run: mvn clean install -DskipTests=false

      # Reporte de pruebas
      - name: Archive test reports
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-reports
          path: target/surefire-reports/*.xml

